version: "3.8"

services:
  db:
    container_name: postgres_week_one
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:

